library(org.Hs.eg.db)
library(clusterProfiler)
args = commandArgs(TRUE)
x = read.table(args[1], sep="\t")		#The input file is a DESeq2 output table where Hsap gene symbols are on column 8
y = enrichGO(x[,8], OrgDb=org.Hs.eg.db, ont="ALL", keyType="SYMBOL", pvalueCutoff = 0.01)
outGO = gsub(".[a-z]+$", "-enrichGO.tsv", args[1])
write.table(y@result, file=outGO, sep="\t", quote=FALSE, row.names=FALSE)
outGOplot = gsub("tsv$", "pdf", outGO)
pdf(outGOplot)
dotplot(y, showCategory=30, font.size=7)
dev.off()

library(ReactomePA)
z = bitr(x[,8], fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Hs.eg.db")
r <- enrichPathway(gene=z[,2], pvalueCutoff = 0.01, readable=TRUE)
outREACT = gsub(".[a-z]+$", "-enrichREACT.tsv", args[1])
write.table(r, file=outREACT, sep="\t", quote=FALSE, row.names=FALSE)
outREACTplot = gsub("tsv$", "pdf", outREACT)
pdf(outREACTplot)
dotplot(r, showCategory=30, font.size=7)
dev.off()

k = enrichKEGG(z[,2], organism="hsa", keyType="ncbi-geneid", pvalueCutoff = 0.01)
outKEGG = gsub(".[a-z]+$", "-enrichKEGG.tsv", args[1])
write.table(k@result, file=outKEGG, sep="\t", quote=FALSE, row.names=FALSE)
outKEGGplot = gsub("tsv$", "pdf", outKEGG)
pdf(outKEGGplot)
dotplot(k, showCategory=30, font.size=7)
dev.off()
